# Generated by Django 5.0.1 on 2025-07-22 16:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Cor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação Geral')),
                ('wifi_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualidade do WiFi')),
                ('power_outlets', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Disponibilidade de Tomadas')),
                ('noise_level', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nível de Ruído (1=Muito Barulhento, 5=Muito Silencioso)')),
                ('comfort', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Conforto')),
                ('location', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Localização')),
                ('value_for_money', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Custo-Benefício')),
                ('food_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualidade da Comida')),
                ('service_quality', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Qualidade do Atendimento')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('visit_date', models.DateField(blank=True, null=True, verbose_name='Data da Visita')),
                ('visit_purpose', models.CharField(blank=True, max_length=100, verbose_name='Propósito da Visita')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/images/', verbose_name='Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workspaces.review', verbose_name='Avaliação')),
            ],
            options={
                'verbose_name': 'Imagem da Avaliação',
                'verbose_name_plural': 'Imagens das Avaliações',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('workspace_type', models.CharField(choices=[('coworking', 'Coworking'), ('cafe', 'Café'), ('library', 'Biblioteca'), ('hotel_lobby', 'Lobby de Hotel'), ('restaurant', 'Restaurante'), ('other', 'Outro')], default='coworking', max_length=20, verbose_name='Tipo de Espaço')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='JSON com horários por dia da semana', verbose_name='Horário de Funcionamento')),
                ('price_range', models.CharField(blank=True, choices=[('free', 'Gratuito'), ('budget', 'Econômico (R$ 1-30)'), ('moderate', 'Moderado (R$ 31-60)'), ('expensive', 'Caro (R$ 61-100)'), ('luxury', 'Luxo (R$ 100+)')], max_length=20, verbose_name='Faixa de Preço')),
                ('daily_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço Diário')),
                ('hourly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Preço por Hora')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='Lista de comodidades disponíveis', verbose_name='Comodidades')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='Reivindicado')),
                ('claim_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da Reivindicação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('favorite_count', models.PositiveIntegerField(default=0, verbose_name='Favoritos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categories', models.ManyToManyField(blank=True, to='workspaces.category', verbose_name='Categorias')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Reivindicado por')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Espaço de Trabalho',
                'verbose_name_plural': 'Espaços de Trabalho',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='workspaces.workspace', verbose_name='Espaço de Trabalho'),
        ),
        migrations.CreateModel(
            name='WorkspaceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_workspaces', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='workspaces.workspace', verbose_name='Espaço de Trabalho')),
            ],
            options={
                'verbose_name': 'Espaço Favorito',
                'verbose_name_plural': 'Espaços Favoritos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workspaces/images/', verbose_name='Imagem')),
                ('image_type', models.CharField(choices=[('main', 'Principal'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('amenity', 'Comodidade'), ('food', 'Comida/Bebida'), ('other', 'Outro')], default='other', max_length=20, verbose_name='Tipo de Imagem')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto Alternativo')),
                ('is_owner_image', models.BooleanField(default=False, verbose_name='Imagem do Proprietário')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='workspaces.workspace', verbose_name='Espaço de Trabalho')),
            ],
            options={
                'verbose_name': 'Imagem do Espaço',
                'verbose_name_plural': 'Imagens dos Espaços',
                'ordering': ['-is_owner_image', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='workspaces.workspace', verbose_name='Espaço de Trabalho')),
            ],
            options={
                'verbose_name': 'Visualização',
                'verbose_name_plural': 'Visualizações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['city', 'state'], name='workspaces__city_56635f_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['workspace_type'], name='workspaces__workspa_44f2cb_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['is_active', 'is_verified'], name='workspaces__is_acti_79caa1_idx'),
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['-created_at'], name='workspaces__created_045d81_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['workspace', '-created_at'], name='workspaces__workspa_9dbf4e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='workspaces__user_id_ba40f0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['overall_rating'], name='workspaces__overall_962dfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('workspace', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='workspacefavorite',
            unique_together={('user', 'workspace')},
        ),
        migrations.AddIndex(
            model_name='workspaceview',
            index=models.Index(fields=['workspace', '-created_at'], name='workspaces__workspa_b6fb74_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceview',
            index=models.Index(fields=['ip_address', '-created_at'], name='workspaces__ip_addr_f12646_idx'),
        ),
    ]
